### ISSUE TITLE
multiple file format for each record

### ISSUE THREAD

**Issue by ClauLung** [dana-apps/dana-core#162] opened 2022-11-26 19:23 UTC
there should be only one media file links to each record, but would be great if we could have a 'duplicate' button to copy all the metadata and upload another media file

**Comment by lanehk** [comment] 2022-11-29 09:43
Claudia - I think we can have multiple media files link to one record. However, I notice that the problem is we can only link images for now - can we do videos and PDFs?

**Comment by lanehk** [comment] 2022-11-29 09:59
also - possible to show asset as a thumbnail please?

**Comment by conatus** [comment] 2022-12-12 19:21
Thumbnail element over here - #172

**Comment by conatus** [comment] 2022-12-12 19:31
Will split out into two further issues.

**Comment by conatus** [comment] 2022-12-14 11:04
Split this into different issues that capture all requirements, so closing out.

**Closed by conatus** 2022-12-14 11:04 UTC
Labels: enhancement, split
